---
- name: Installing the monitoring software
  hosts: all
  tasks:
    - name: clone gitlab directory
      git:
        repo: https://{{token_name}}:{{access_token}}@{{gitlab_address}}
        dest: /bin/monitoring
      become: true

    - name: add the .env with the right values
      template:
        src: .env.template.j2
        dest: /bin/monitoring/.env
      become: true

    - name: Install pip3, to install the requirements
      ansible.builtin.apt:
        name: python3-pip
        state: present
      become: true

    - name: install the requirements
      ansible.builtin.pip:
        requirements: "/bin/monitoring/requirements.txt"
      become: true

    - name: add a service for the program
      template:
        src: collector.service.j2
        dest: /etc/systemd/system/collector.service
      become: true

    - name: enable the service
      ansible.builtin.systemd:
        name: collector
        enabled: true
      become: true

    - name: start the service
      ansible.builtin.systemd:
        name: collector
        state: started
      become: true
...
