---
- name: Installing the monitoring software
  hosts: localhost
  connection: local
  tasks:
    - name: clone gitlab directory
      git:
        repo: https://{{token_name}}:{{access_token}}@{{gitlab_address}}
        dest: /bin/monitoring
      become: true

    - name: add the .env with the right values
      template:
        src: .env.template.j2
        dest: /bin/monitoring/.env

    - name: add the main method to CRON
      ansible.builtin.cron:
        name: "Monitoring software"
        special_time: reboot
        job: "/bin/monitoring/main.py"

    - name: install the requirements
      ansible.builtin.pip:
        requirements: "/bin/monitoring/requirements.txt"

    - name: start the application
      command:  "python3 /bin/monitoring/main.py"
...
